parameters:
  remove_temporary_folder: true
  perform_dry_run: true

flows:
  fb7zs3-flow:
    description: "Backup of firebird databases with further compression using 7z and upload to the S3 storage"

    steps:
      - name: "mkdir_for_backup"
        description: "Makes directory for backup output"
        generation_mask: "{{yabtool_exec_folder}}/{{main_database_name}}/{{backup_start_timestamp|extract_year_four_digits}}-{{backup_start_timestamp|extract_month_two_digits}}-{{backup_start_timestamp|extract_day_two_digits}}_{{main_database_name}}_backup"
        generates:
          output_folder_name: "{{result}}"
      - name: "firebird_backup"
#        command_template: "gbak -backup_database -user {{user_name}} -password {{password}} -verbose -y {{output_folder_name}}/{{backup_log_name}} {{database_host}}:{{database_path}} {{output_folder_name}}/{{backup_file_name}}"
        command_template: "gbak -backup_database -user {{user_name}} -password {{password}} -metadata -verbose -y {{output_folder_name}}/{{backup_log_name}} {{database_host}}:{{database_path}} {{output_folder_name}}/{{backup_file_name}}"
        backup_log_name: "backup.log"
        backup_file_name: "{{main_database_name}}.fbk"
        dry_run_command: "gbak -z"
        generates:
          backup_file_name: "{{backup_file_name}}"
      - name: "calculate_file_hash_and_save_in_file"
        input_file_name: "{{output_folder_name}}/{{backup_file_name}}"
        output_file_name: "{{output_folder_name}}/{{backup_file_name}}.sha256"
        file_name_in_validation_file: "{{backup_file_name}}"
        hash_type: "sha256"
      - name: "7z_compress"
        command_template: "7z a {{output_archive_name}} -p{{archive_password}} -mhe -t7z  {{output_folder_name}}"
        output_archive_name: "{{output_folder_name}}.7z"
        dry_run_command: "7z"
        generates:
          output_archive_extension: "7z"
          output_archive_name: "{{output_archive_name}}"
      - name: "calculate_file_hash_and_save_in_file"
        input_file_name: "{{output_archive_name}}"
        output_file_name: "{{output_archive_name}}.sha256"
        file_name_in_validation_file: "{{backup_file_name}}"
        hash_type: "sha256"
        generates:
          output_archive_hash_file_name: "{{output_file_name}}"
      - name: "validate_7z_archive"
        command_template: "7z t {{output_archive_name}} * -r -p{{archive_password}}"
        dry_run_command: "7z"
        relative_secrets:
          - 7z_compress
      - name: "s3_multipart_upload"
        database_prefix_in_bucket: "backups/{{main_database_name}}"
        source_files:
          - source_file: "{{output_archive_name}}"
          - source_file: "{{output_archive_hash_file_name}}"
        upload_rules:
          - name: "weekdays"
            description: "upload for week day name, one per each weekday"
            destination_prefix: "{{database_prefix_in_bucket}}/weekdays/{{week_day_short_name | lower}}"
            validation_name: "flag_{{week_day_short_name | lower}}_{{main_database_name | lower}}.{{output_archive_extension | lower}}"
          - name: "weekly"
            description: "upload per week number in year"
            destination_prefix: "{{database_prefix_in_bucket}}/weeks/{{week_number}}"
            validation_name: "flag_{{current_year}}_{{week_number}}_{{main_database_name}}.{{output_archive_extension}}"
          - name: "monthly"
            description: "upload per month name"
            destination_prefix: "{{database_prefix_in_bucket}}/monthly/{{current_year}}/{{month_short_name | lower}}"
            validation_name: "flag_{{current_year}}_{{month_short_name | lower}}_{{main_database_name}}.{{output_archive_extension}}"
